// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDveKiIx97BXyHcSdev9GkyboygaeaZe68',
    appId: '1:32977242957:web:2b09fe0dcef342158c0504',
    messagingSenderId: '32977242957',
    projectId: 'scrubtofitness',
    authDomain: 'scrubtofitness.firebaseapp.com',
    storageBucket: 'scrubtofitness.appspot.com',
    measurementId: 'G-L6DFC3L6RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyDN3PdIrB7EjnnaYQNmczoga8Wca98jk',
    appId: '1:32977242957:android:d590c2e310876daa8c0504',
    messagingSenderId: '32977242957',
    projectId: 'scrubtofitness',
    storageBucket: 'scrubtofitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOW6_XChAPHYt8kwyXq1rppu9GJd-kkyQ',
    appId: '1:32977242957:ios:8824a39a524e90a08c0504',
    messagingSenderId: '32977242957',
    projectId: 'scrubtofitness',
    storageBucket: 'scrubtofitness.appspot.com',
    androidClientId: '32977242957-hjdeoof42setelotagopecjmpp64ovs4.apps.googleusercontent.com',
    iosClientId: '32977242957-tdo488coescdpvrhhogu00unknc7pm7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrubtofit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOW6_XChAPHYt8kwyXq1rppu9GJd-kkyQ',
    appId: '1:32977242957:ios:8824a39a524e90a08c0504',
    messagingSenderId: '32977242957',
    projectId: 'scrubtofitness',
    storageBucket: 'scrubtofitness.appspot.com',
    androidClientId: '32977242957-hjdeoof42setelotagopecjmpp64ovs4.apps.googleusercontent.com',
    iosClientId: '32977242957-tdo488coescdpvrhhogu00unknc7pm7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrubtofit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDveKiIx97BXyHcSdev9GkyboygaeaZe68',
    appId: '1:32977242957:web:802e2a3aa5f9aaaf8c0504',
    messagingSenderId: '32977242957',
    projectId: 'scrubtofitness',
    authDomain: 'scrubtofitness.firebaseapp.com',
    storageBucket: 'scrubtofitness.appspot.com',
    measurementId: 'G-EJC4Z4RPTX',
  );

}